// Generated by scripts/convert_wiki_tables.py
window.REQUIREMENT_TRACKER_DATA = {
  "uiIcons": {
    "cards": {
      "Explosives Station": "https://arcraiders.wiki/w/images/7/78/Icon_Grenade.png",
      "Gear Bench": "https://arcraiders.wiki/w/images/a/aa/Icon_Shield.png",
      "Gunsmith": "https://arcraiders.wiki/w/images/5/5c/Icon_WeaponMod.png",
      "Medical Lab": "https://arcraiders.wiki/w/images/b/ba/Icon_Regenerative.png",
      "Refiner": "https://arcraiders.wiki/w/images/d/d0/Icon_Refiner.png",
      "Scrappy": "https://arcraiders.wiki/w/images/6/6d/Icon_Scrappy.png",
      "Utility Station": "https://arcraiders.wiki/w/images/7/7e/Icon_Utility.png",
      "Expedition": "https://arcraiders.wiki/w/images/d/d4/Expedition_1_Indicator_Icon.png"
    },
    "foundIn": {
      "ARC": "https://arcraiders.wiki/w/images/9/96/Icon_ARC.png",
      "Commercial": "https://arcraiders.wiki/w/images/e/e3/Icon_Commercial.png",
      "Electrical": "https://arcraiders.wiki/w/images/6/6e/Icon_Electrical.png",
      "Exodus": "https://arcraiders.wiki/w/images/b/b7/Icon_Exodus.png",
      "Industrial": "https://arcraiders.wiki/w/images/e/ef/Icon_Industrial.png",
      "Mechanical": "https://arcraiders.wiki/w/images/0/02/Icon_Mechanical.png",
      "Medical": "https://arcraiders.wiki/w/images/f/fc/Icon_Medical.png",
      "Nature": "https://arcraiders.wiki/w/images/5/54/Icon_Nature.png",
      "Old World": "https://arcraiders.wiki/w/images/e/eb/Icon_Old_World.png",
      "Residential": "https://arcraiders.wiki/w/images/8/8e/Icon_Residential.png",
      "Security": "https://arcraiders.wiki/w/images/4/43/Icon_Security.png",
      "Technological": "https://arcraiders.wiki/w/images/8/8f/Icon_Technological.png"
    }
  },
  "stations": [
    {
      "station": "Explosives Station",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "iconUrl": "https://arcraiders.wiki/w/images/7/78/Icon_Grenade.png",
      "minLevel": 0,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Chemicals",
              "quantity": 50
            },
            {
              "item": "ARC Alloy",
              "quantity": 6
            }
          ],
          "crafts": [
            "Gas Grenade",
            "Light Impact Grenade"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Synthesized Fuel",
              "quantity": 3
            },
            {
              "item": "Crude Explosives",
              "quantity": 5
            },
            {
              "item": "Pop Trigger",
              "quantity": 5
            }
          ],
          "crafts": [
            "Blaze Grenade",
            "Shrapnel Grenade",
            "Snap Blast Grenade"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Laboratory Reagents",
              "quantity": 3
            },
            {
              "item": "Explosive Compound",
              "quantity": 5
            },
            {
              "item": "Rocketeer Driver",
              "quantity": 3
            }
          ],
          "crafts": [
            "Heavy Fuze Grenade",
            "Explosive Mine",
            "Wolfpack"
          ]
        }
      ],
      "maxLevel": 3
    },
    {
      "station": "Gear Bench",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "iconUrl": "https://arcraiders.wiki/w/images/a/aa/Icon_Shield.png",
      "minLevel": 0,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Plastic Parts",
              "quantity": 25
            },
            {
              "item": "Fabric",
              "quantity": 30
            }
          ],
          "crafts": [
            "Light Shield",
            "Medium Shield",
            "Combat Mk. 1",
            "Looting Mk. 1",
            "Tactical Mk. 1"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Power Cable",
              "quantity": 3
            },
            {
              "item": "Electrical Components",
              "quantity": 5
            },
            {
              "item": "Hornet Driver",
              "quantity": 5
            }
          ],
          "crafts": [
            "Heavy Shield",
            "Combat Mk. 2",
            "Looting Mk. 2",
            "Tactical Mk. 2"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Industrial Battery",
              "quantity": 3
            },
            {
              "item": "Advanced Electrical Components",
              "quantity": 5
            },
            {
              "item": "Bastion Cell",
              "quantity": 6
            }
          ],
          "crafts": [
            "Combat Mk. 3 (Aggressive)",
            "Combat Mk. 3 (Flanking)",
            "Looting Mk. 3 (Cautious)",
            "Looting Mk. 3 (Survivor)",
            "Tactical Mk. 3 (Defensive)",
            "Tactical Mk. 3 (Healing)"
          ]
        }
      ],
      "maxLevel": 3
    },
    {
      "station": "Gunsmith",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "iconUrl": "https://arcraiders.wiki/w/images/5/5c/Icon_WeaponMod.png",
      "minLevel": 0,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Metal Parts",
              "quantity": 20
            },
            {
              "item": "Rubber Parts",
              "quantity": 30
            }
          ],
          "crafts": [
            "Ferro",
            "Hairpin",
            "Kettle",
            "Rattler",
            "Stitcher",
            "Angled Grip I",
            "Compensator I",
            "Extended Light Mag I",
            "Extended Medium Mag I",
            "Extended Shotgun Mag I",
            "Muzzle Brake I",
            "Shotgun Choke I",
            "Stable Stock I",
            "Vertical Grip I"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Rusted Tools",
              "quantity": 3
            },
            {
              "item": "Mechanical Components",
              "quantity": 5
            },
            {
              "item": "Wasp Driver",
              "quantity": 8
            }
          ],
          "crafts": [
            "Arpeggio"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Rusted Gear",
              "quantity": 3
            },
            {
              "item": "Advanced Mechanical Components",
              "quantity": 5
            },
            {
              "item": "Sentinel Firing Core",
              "quantity": 4
            }
          ],
          "crafts": [
            "Bettina",
            "Renegade",
            "Hullcracker"
          ]
        }
      ],
      "maxLevel": 3
    },
    {
      "station": "Medical Lab",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "iconUrl": "https://arcraiders.wiki/w/images/b/ba/Icon_Regenerative.png",
      "minLevel": 0,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Fabric",
              "quantity": 50
            },
            {
              "item": "ARC Alloy",
              "quantity": 6
            }
          ],
          "crafts": [
            "Herbal Bandage",
            "Shield Recharger",
            "Adrenaline Shot",
            "Bandage"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Cracked Bioscanner",
              "quantity": 2
            },
            {
              "item": "Durable Cloth",
              "quantity": 5
            },
            {
              "item": "Tick Pod",
              "quantity": 8
            }
          ],
          "crafts": [
            "Sterilized Bandage",
            "Surge Shield Recharger"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Rusted Shut Medical Kit",
              "quantity": 3
            },
            {
              "item": "Antiseptic",
              "quantity": 8
            },
            {
              "item": "Surveyor Vault",
              "quantity": 5
            }
          ],
          "crafts": [
            "Vita Spray",
            "Vita Shot"
          ]
        }
      ],
      "maxLevel": 3
    },
    {
      "station": "Refiner",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "iconUrl": "https://arcraiders.wiki/w/images/d/d0/Icon_Refiner.png",
      "minLevel": 0,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Metal Parts",
              "quantity": 60
            },
            {
              "item": "ARC Powercell",
              "quantity": 5
            }
          ],
          "crafts": [
            "Crude Explosives",
            "Durable Cloth",
            "Electrical Components",
            "Mechanical Components"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Toaster",
              "quantity": 3
            },
            {
              "item": "ARC Motion Core",
              "quantity": 5
            },
            {
              "item": "Fireball Burner",
              "quantity": 8
            }
          ],
          "crafts": [
            "Advanced Electrical Components",
            "Advanced Mechanical Components",
            "Antiseptic",
            "ARC Circuitry",
            "ARC Motion Core",
            "Explosive Compound",
            "Heavy Gun Parts",
            "Light Gun Parts",
            "Medium Gun Parts",
            "Mod Components"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Motor",
              "quantity": 3
            },
            {
              "item": "ARC Circuitry",
              "quantity": 10
            },
            {
              "item": "Bombardier Cell",
              "quantity": 6
            }
          ],
          "crafts": [
            "Magnetic Accelerator",
            "Power Rod",
            "Complex Gun Parts"
          ]
        }
      ],
      "maxLevel": 3
    },
    {
      "station": "Utility Station",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "iconUrl": "https://arcraiders.wiki/w/images/7/7e/Icon_Utility.png",
      "minLevel": 0,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Plastic Parts",
              "quantity": 50
            },
            {
              "item": "ARC Alloy",
              "quantity": 6
            }
          ],
          "crafts": [
            "Barricade Kit",
            "Binoculars",
            "Door Blocker",
            "Firecracker",
            "Li'l Smoke Grenade",
            "Remote Raider Flare",
            "Smoke Grenade"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Damaged Heat Sink",
              "quantity": 2
            },
            {
              "item": "Electrical Components",
              "quantity": 5
            },
            {
              "item": "Snitch Scanner",
              "quantity": 6
            }
          ],
          "crafts": [
            "Lure Grenade",
            "Raider Hatch Key",
            "Zipline"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Fried Motherboard",
              "quantity": 3
            },
            {
              "item": "Advanced Electrical Components",
              "quantity": 5
            },
            {
              "item": "Leaper Pulse Unit",
              "quantity": 4
            }
          ],
          "crafts": [
            "Photoelectric Cloak",
            "Snap Hook",
            "Tagging Grenade"
          ]
        }
      ],
      "maxLevel": 3
    }
  ],
  "scrappy": {
    "station": "Scrappy",
    "kindLabel": "Companion",
    "scope": "scrappy",
    "iconFilename": "Icon_Scrappy.png",
    "minLevel": 1,
    "maxLevel": 5,
    "levels": [
      {
        "level": 1,
        "requirements": [],
        "crafts": []
      },
      {
        "level": 2,
        "requirements": [
          {
            "item": "Dog Collar",
            "quantity": 1
          }
        ],
        "crafts": []
      },
      {
        "level": 3,
        "requirements": [
          {
            "item": "Lemon",
            "quantity": 3
          },
          {
            "item": "Apricot",
            "quantity": 3
          }
        ],
        "crafts": []
      },
      {
        "level": 4,
        "requirements": [
          {
            "item": "Prickly Pear",
            "quantity": 6
          },
          {
            "item": "Olives",
            "quantity": 6
          },
          {
            "item": "Cat Bed",
            "quantity": 1
          }
        ],
        "crafts": []
      },
      {
        "level": 5,
        "requirements": [
          {
            "item": "Mushroom",
            "quantity": 12
          },
          {
            "item": "Apricot",
            "quantity": 12
          },
          {
            "item": "Very Comfortable Pillow",
            "quantity": 3
          }
        ],
        "crafts": []
      }
    ],
    "iconUrl": "https://arcraiders.wiki/w/images/6/6d/Icon_Scrappy.png"
  },
  "expedition": {
    "station": "Expedition",
    "kindLabel": "Project",
    "scope": "expedition",
    "iconFilename": "Expedition 1 Indicator Icon.png",
    "variants": [
      {
        "id": "expedition-1",
        "label": "Expedition 1",
        "minLevel": 0,
        "maxLevel": 4,
        "zeroLabel": "Not started",
        "completeLabel": "Outfitting complete",
        "levels": [
          {
            "level": 1,
            "label": "Foundation (1/6)",
            "progressLabel": "Foundation complete",
            "description": "Building the base structure and frame of the caravan.",
            "requirements": [
              {
                "item": "Metal Parts",
                "quantity": 150
              },
              {
                "item": "Rubber Parts",
                "quantity": 200
              },
              {
                "item": "ARC Alloy",
                "quantity": 80
              },
              {
                "item": "Steel Spring",
                "quantity": 15
              }
            ],
            "crafts": []
          },
          {
            "level": 2,
            "label": "Core Systems (2/6)",
            "progressLabel": "Core Systems complete",
            "description": "Connecting wiring, ventilation, and essential power systems.",
            "requirements": [
              {
                "item": "Durable Cloth",
                "quantity": 35
              },
              {
                "item": "Wires",
                "quantity": 30
              },
              {
                "item": "Electrical Components",
                "quantity": 30
              },
              {
                "item": "Cooling Fan",
                "quantity": 5
              }
            ],
            "crafts": []
          },
          {
            "level": 3,
            "label": "Framework (3/6)",
            "progressLabel": "Framework complete",
            "description": "Building walls and roof, installing core systems, and defining the interior layout.",
            "requirements": [
              {
                "item": "Light Bulb",
                "quantity": 5
              },
              {
                "item": "Battery",
                "quantity": 30
              },
              {
                "item": "Sensors",
                "quantity": 20
              },
              {
                "item": "Exodus Modules",
                "quantity": 1
              }
            ],
            "crafts": []
          },
          {
            "level": 4,
            "label": "Outfitting (4/6)",
            "progressLabel": "Outfitting complete",
            "description": "Adding storage, workbenches, utilities, and personal touches.",
            "requirements": [
              {
                "item": "Humidifier",
                "quantity": 5
              },
              {
                "item": "Advanced Electrical Components",
                "quantity": 5
              },
              {
                "item": "Magnetic Accelerator",
                "quantity": 3
              },
              {
                "item": "Leaper Pulse Unit",
                "quantity": 3
              }
            ],
            "crafts": []
          }
        ]
      },
      {
        "id": "expedition-2",
        "label": "Expedition 2",
        "minLevel": 0,
        "maxLevel": 4,
        "zeroLabel": "Not started",
        "completeLabel": "Outfitting complete",
        "levels": [
          {
            "level": 1,
            "label": "Foundation (1/6)",
            "progressLabel": "Foundation complete",
            "description": "Building the base structure and frame of the caravan.",
            "requirements": [
              {
                "item": "Metal Parts",
                "quantity": 150
              },
              {
                "item": "Plastic Parts",
                "quantity": 200
              },
              {
                "item": "ARC Alloy",
                "quantity": 80
              },
              {
                "item": "Steel Spring",
                "quantity": 15
              }
            ],
            "crafts": []
          },
          {
            "level": 2,
            "label": "Core Systems (2/6)",
            "progressLabel": "Core Systems complete",
            "description": "Connecting wiring, ventilation, and essential power systems.",
            "requirements": [
              {
                "item": "Durable Cloth",
                "quantity": 35
              },
              {
                "item": "Wires",
                "quantity": 25
              },
              {
                "item": "Electrical Components",
                "quantity": 20
              },
              {
                "item": "Cooling Coil",
                "quantity": 4
              }
            ],
            "crafts": []
          },
          {
            "level": 3,
            "label": "Framework (3/6)",
            "progressLabel": "Framework complete",
            "description": "Building walls and roof, installing core systems, and defining the interior layout.",
            "requirements": [
              {
                "item": "Light Bulb",
                "quantity": 4
              },
              {
                "item": "Battery",
                "quantity": 30
              },
              {
                "item": "Shredder Gyro",
                "quantity": 10
              },
              {
                "item": "Exodus Modules",
                "quantity": 1
              }
            ],
            "crafts": []
          },
          {
            "level": 4,
            "label": "Outfitting (4/6)",
            "progressLabel": "Outfitting complete",
            "description": "Adding storage, workbenches, utilities, and personal touches.",
            "requirements": [
              {
                "item": "Frequency Modulation Box",
                "quantity": 5
              },
              {
                "item": "Advanced Electrical Components",
                "quantity": 5
              },
              {
                "item": "Ion Sputter",
                "quantity": 3
              },
              {
                "item": "Leaper Pulse Unit",
                "quantity": 3
              }
            ],
            "crafts": []
          }
        ]
      },
      {
        "id": "expedition-3",
        "label": "Expedition 3",
        "minLevel": 0,
        "maxLevel": 4,
        "zeroLabel": "Not started",
        "completeLabel": "Outfitting complete",
        "levels": [
          {
            "level": 1,
            "label": "Foundation (1/6)",
            "progressLabel": "Foundation complete",
            "description": "Building the base structure and frame of the caravan.",
            "requirements": [
              {
                "item": "Metal Parts",
                "quantity": 150
              },
              {
                "item": "Chemicals",
                "quantity": 100
              },
              {
                "item": "ARC Alloy",
                "quantity": 80
              },
              {
                "item": "Steel Spring",
                "quantity": 15
              }
            ],
            "crafts": []
          },
          {
            "level": 2,
            "label": "Core Systems (2/6)",
            "progressLabel": "Core Systems complete",
            "description": "Connecting wiring, ventilation, and essential power systems.",
            "requirements": [
              {
                "item": "Durable Cloth",
                "quantity": 30
              },
              {
                "item": "Wires",
                "quantity": 25
              },
              {
                "item": "Electrical Components",
                "quantity": 20
              },
              {
                "item": "Industrial Charger",
                "quantity": 3
              }
            ],
            "crafts": []
          },
          {
            "level": 3,
            "label": "Framework (3/6)",
            "progressLabel": "Framework complete",
            "description": "Building walls and roof, installing core systems, and defining the interior layout.",
            "requirements": [
              {
                "item": "Coffee Pot",
                "quantity": 1
              },
              {
                "item": "Battery",
                "quantity": 25
              },
              {
                "item": "Firefly Burner",
                "quantity": 5
              },
              {
                "item": "Exodus Modules",
                "quantity": 1
              }
            ],
            "crafts": []
          },
          {
            "level": 4,
            "label": "Outfitting (4/6)",
            "progressLabel": "Outfitting complete",
            "description": "Adding storage, workbenches, utilities, and personal touches.",
            "requirements": [
              {
                "item": "Broken Guidance System",
                "quantity": 1
              },
              {
                "item": "Advanced Electrical Components",
                "quantity": 5
              },
              {
                "item": "Breathtaking Snow Globe",
                "quantity": 3
              },
              {
                "item": "Bombardier Cell",
                "quantity": 2
              }
            ],
            "crafts": []
          }
        ]
      }
    ],
    "iconUrl": "https://arcraiders.wiki/w/images/d/d4/Expedition_1_Indicator_Icon.png"
  }
};
