// Generated by scripts/convert_wiki_tables.py
window.REQUIREMENT_TRACKER_DATA = {
  "schemaVersion": 2,
  "generatedAt": "2026-03-31T02:42:22.076452+00:00",
  "buildId": "af57e965",
  "uiIcons": {
    "cards": {
      "Workbench": "https://arcraiders.wiki/w/images/c/c9/Icon_Workbench.png",
      "Explosives Station": "https://arcraiders.wiki/w/images/7/78/Icon_Grenade.png",
      "Gear Bench": "https://arcraiders.wiki/w/images/a/aa/Icon_Shield.png",
      "Gunsmith": "https://arcraiders.wiki/w/images/5/5c/Icon_WeaponMod.png",
      "Medical Lab": "https://arcraiders.wiki/w/images/b/ba/Icon_Regenerative.png",
      "Refiner": "https://arcraiders.wiki/w/images/d/d0/Icon_Refiner.png",
      "Scrappy": "https://arcraiders.wiki/w/images/6/6d/Icon_Scrappy.png",
      "Utility Station": "https://arcraiders.wiki/w/images/7/7e/Icon_Utility.png",
      "Expedition": "https://arcraiders.wiki/w/images/d/d4/Expedition_1_Indicator_Icon.png"
    },
    "foundIn": {
      "ARC": "https://arcraiders.wiki/w/images/9/96/Icon_ARC.png",
      "Commercial": "https://arcraiders.wiki/w/images/e/e3/Icon_Commercial.png",
      "Electrical": "https://arcraiders.wiki/w/images/6/6e/Icon_Electrical.png",
      "Exodus": "https://arcraiders.wiki/w/images/b/b7/Icon_Exodus.png",
      "Industrial": "https://arcraiders.wiki/w/images/e/ef/Icon_Industrial.png",
      "Mechanical": "https://arcraiders.wiki/w/images/0/02/Icon_Mechanical.png",
      "Medical": "https://arcraiders.wiki/w/images/f/fc/Icon_Medical.png",
      "Nature": "https://arcraiders.wiki/w/images/5/54/Icon_Nature.png",
      "Old World": "https://arcraiders.wiki/w/images/e/eb/Icon_Old_World.png",
      "Residential": "https://arcraiders.wiki/w/images/8/8e/Icon_Residential.png",
      "Security": "https://arcraiders.wiki/w/images/4/43/Icon_Security.png",
      "Technological": "https://arcraiders.wiki/w/images/8/8f/Icon_Technological.png"
    }
  },
  "cards": [
    {
      "id": "workshop-explosives-station",
      "title": "Explosives Station",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "sortOrder": 0,
      "iconUrl": "https://arcraiders.wiki/w/images/7/78/Icon_Grenade.png",
      "minLevel": 0,
      "maxLevel": 3,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Chemicals",
              "quantity": 50
            },
            {
              "item": "ARC Alloy",
              "quantity": 6
            }
          ],
          "crafts": [
            "Gas Grenade",
            "Light Impact Grenade"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Synthesized Fuel",
              "quantity": 3
            },
            {
              "item": "Crude Explosives",
              "quantity": 5
            },
            {
              "item": "Pop Trigger",
              "quantity": 5
            }
          ],
          "crafts": [
            "Blaze Grenade",
            "Shrapnel Grenade",
            "Snap Blast Grenade"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Laboratory Reagents",
              "quantity": 3
            },
            {
              "item": "Explosive Compound",
              "quantity": 5
            },
            {
              "item": "Rocketeer Driver",
              "quantity": 3
            }
          ],
          "crafts": [
            "Heavy Fuze Grenade",
            "Explosive Mine",
            "Wolfpack"
          ]
        }
      ]
    },
    {
      "id": "workshop-gear-bench",
      "title": "Gear Bench",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "sortOrder": 0,
      "iconUrl": "https://arcraiders.wiki/w/images/a/aa/Icon_Shield.png",
      "minLevel": 0,
      "maxLevel": 3,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Plastic Parts",
              "quantity": 25
            },
            {
              "item": "Fabric",
              "quantity": 30
            }
          ],
          "crafts": [
            "Light Shield",
            "Medium Shield",
            "Combat Mk. 1",
            "Looting Mk. 1",
            "Tactical Mk. 1"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Power Cable",
              "quantity": 3
            },
            {
              "item": "Electrical Components",
              "quantity": 5
            },
            {
              "item": "Hornet Driver",
              "quantity": 5
            }
          ],
          "crafts": [
            "Heavy Shield",
            "Combat Mk. 2",
            "Looting Mk. 2",
            "Tactical Mk. 2"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Industrial Battery",
              "quantity": 3
            },
            {
              "item": "Advanced Electrical Components",
              "quantity": 5
            },
            {
              "item": "Bastion Cell",
              "quantity": 6
            }
          ],
          "crafts": [
            "Combat Mk. 3 (Aggressive)",
            "Combat Mk. 3 (Flanking)",
            "Looting Mk. 3 (Cautious)",
            "Looting Mk. 3 (Survivor)",
            "Tactical Mk. 3 (Defensive)",
            "Tactical Mk. 3 (Healing)"
          ]
        }
      ]
    },
    {
      "id": "workshop-gunsmith",
      "title": "Gunsmith",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "sortOrder": 0,
      "iconUrl": "https://arcraiders.wiki/w/images/5/5c/Icon_WeaponMod.png",
      "minLevel": 0,
      "maxLevel": 3,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Metal Parts",
              "quantity": 20
            },
            {
              "item": "Rubber Parts",
              "quantity": 30
            }
          ],
          "crafts": [
            "Ferro",
            "Hairpin",
            "Kettle",
            "Rattler",
            "Stitcher",
            "Angled Grip I",
            "Compensator I",
            "Extended Light Mag I",
            "Extended Medium Mag I",
            "Extended Shotgun Mag I",
            "Muzzle Brake I",
            "Shotgun Choke I",
            "Stable Stock I",
            "Vertical Grip I"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Rusted Tools",
              "quantity": 3
            },
            {
              "item": "Mechanical Components",
              "quantity": 5
            },
            {
              "item": "Wasp Driver",
              "quantity": 8
            }
          ],
          "crafts": [
            "Arpeggio"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Rusted Gear",
              "quantity": 3
            },
            {
              "item": "Advanced Mechanical Components",
              "quantity": 5
            },
            {
              "item": "Sentinel Firing Core",
              "quantity": 4
            }
          ],
          "crafts": [
            "Bettina",
            "Renegade",
            "Hullcracker"
          ]
        }
      ]
    },
    {
      "id": "workshop-medical-lab",
      "title": "Medical Lab",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "sortOrder": 0,
      "iconUrl": "https://arcraiders.wiki/w/images/b/ba/Icon_Regenerative.png",
      "minLevel": 0,
      "maxLevel": 3,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Fabric",
              "quantity": 50
            },
            {
              "item": "ARC Alloy",
              "quantity": 6
            }
          ],
          "crafts": [
            "Herbal Bandage",
            "Shield Recharger",
            "Adrenaline Shot",
            "Bandage"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Cracked Bioscanner",
              "quantity": 2
            },
            {
              "item": "Durable Cloth",
              "quantity": 5
            },
            {
              "item": "Tick Pod",
              "quantity": 8
            }
          ],
          "crafts": [
            "Sterilized Bandage",
            "Surge Shield Recharger"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Rusted Shut Medical Kit",
              "quantity": 3
            },
            {
              "item": "Antiseptic",
              "quantity": 8
            },
            {
              "item": "Surveyor Vault",
              "quantity": 5
            }
          ],
          "crafts": [
            "Vita Spray",
            "Vita Shot"
          ]
        }
      ]
    },
    {
      "id": "workshop-refiner",
      "title": "Refiner",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "sortOrder": 0,
      "iconUrl": "https://arcraiders.wiki/w/images/d/d0/Icon_Refiner.png",
      "minLevel": 0,
      "maxLevel": 3,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Metal Parts",
              "quantity": 60
            },
            {
              "item": "ARC Powercell",
              "quantity": 5
            }
          ],
          "crafts": [
            "Crude Explosives",
            "Durable Cloth",
            "Electrical Components",
            "Mechanical Components"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Toaster",
              "quantity": 3
            },
            {
              "item": "ARC Motion Core",
              "quantity": 5
            },
            {
              "item": "Fireball Burner",
              "quantity": 8
            }
          ],
          "crafts": [
            "Advanced Electrical Components",
            "Advanced Mechanical Components",
            "Antiseptic",
            "ARC Circuitry",
            "ARC Motion Core",
            "Explosive Compound",
            "Heavy Gun Parts",
            "Light Gun Parts",
            "Medium Gun Parts",
            "Mod Components"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Motor",
              "quantity": 3
            },
            {
              "item": "ARC Circuitry",
              "quantity": 10
            },
            {
              "item": "Bombardier Cell",
              "quantity": 6
            }
          ],
          "crafts": [
            "Magnetic Accelerator",
            "Power Rod",
            "Complex Gun Parts"
          ]
        }
      ]
    },
    {
      "id": "workshop-utility-station",
      "title": "Utility Station",
      "kindLabel": "Workshop",
      "scope": "workshops",
      "sortOrder": 0,
      "iconUrl": "https://arcraiders.wiki/w/images/7/7e/Icon_Utility.png",
      "minLevel": 0,
      "maxLevel": 3,
      "levels": [
        {
          "level": 1,
          "requirements": [
            {
              "item": "Plastic Parts",
              "quantity": 50
            },
            {
              "item": "ARC Alloy",
              "quantity": 6
            }
          ],
          "crafts": [
            "Barricade Kit",
            "Binoculars",
            "Door Blocker",
            "Firecracker",
            "Li'l Smoke Grenade",
            "Remote Raider Flare",
            "Smoke Grenade"
          ]
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Damaged Heat Sink",
              "quantity": 2
            },
            {
              "item": "Electrical Components",
              "quantity": 5
            },
            {
              "item": "Snitch Scanner",
              "quantity": 6
            }
          ],
          "crafts": [
            "Lure Grenade",
            "Raider Hatch Key",
            "Zipline"
          ]
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Fried Motherboard",
              "quantity": 3
            },
            {
              "item": "Advanced Electrical Components",
              "quantity": 5
            },
            {
              "item": "Leaper Pulse Unit",
              "quantity": 4
            }
          ],
          "crafts": [
            "Photoelectric Cloak",
            "Snap Hook",
            "Tagging Grenade"
          ]
        }
      ]
    },
    {
      "id": "scrappy",
      "title": "Scrappy",
      "kindLabel": "Companion",
      "scope": "scrappy",
      "sortOrder": 10,
      "iconUrl": "https://arcraiders.wiki/w/images/6/6d/Icon_Scrappy.png",
      "minLevel": 1,
      "levels": [
        {
          "level": 1,
          "requirements": [],
          "crafts": []
        },
        {
          "level": 2,
          "requirements": [
            {
              "item": "Dog Collar",
              "quantity": 1
            }
          ],
          "crafts": []
        },
        {
          "level": 3,
          "requirements": [
            {
              "item": "Lemon",
              "quantity": 3
            },
            {
              "item": "Apricot",
              "quantity": 3
            }
          ],
          "crafts": []
        },
        {
          "level": 4,
          "requirements": [
            {
              "item": "Prickly Pear",
              "quantity": 6
            },
            {
              "item": "Olives",
              "quantity": 6
            },
            {
              "item": "Cat Bed",
              "quantity": 1
            }
          ],
          "crafts": []
        },
        {
          "level": 5,
          "requirements": [
            {
              "item": "Mushroom",
              "quantity": 12
            },
            {
              "item": "Apricot",
              "quantity": 12
            },
            {
              "item": "Very Comfortable Pillow",
              "quantity": 3
            }
          ],
          "crafts": []
        }
      ],
      "maxLevel": 5
    },
    {
      "id": "expedition",
      "title": "Expedition",
      "kindLabel": "Project",
      "scope": "expedition",
      "sortOrder": 20,
      "iconUrl": "https://arcraiders.wiki/w/images/d/d4/Expedition_1_Indicator_Icon.png",
      "variants": [
        {
          "id": "expedition-1",
          "title": "Expedition 1",
          "minLevel": 0,
          "zeroLabel": "Not started",
          "completeLabel": "Outfitting complete",
          "levels": [
            {
              "level": 1,
              "requirements": [
                {
                  "item": "Metal Parts",
                  "quantity": 150
                },
                {
                  "item": "Rubber Parts",
                  "quantity": 200
                },
                {
                  "item": "ARC Alloy",
                  "quantity": 80
                },
                {
                  "item": "Steel Spring",
                  "quantity": 15
                }
              ],
              "crafts": [],
              "label": "Foundation (1/6)",
              "progressLabel": "Foundation complete",
              "description": "Building the base structure and frame of the caravan."
            },
            {
              "level": 2,
              "requirements": [
                {
                  "item": "Durable Cloth",
                  "quantity": 35
                },
                {
                  "item": "Wires",
                  "quantity": 30
                },
                {
                  "item": "Electrical Components",
                  "quantity": 30
                },
                {
                  "item": "Cooling Fan",
                  "quantity": 5
                }
              ],
              "crafts": [],
              "label": "Core Systems (2/6)",
              "progressLabel": "Core Systems complete",
              "description": "Connecting wiring, ventilation, and essential power systems."
            },
            {
              "level": 3,
              "requirements": [
                {
                  "item": "Light Bulb",
                  "quantity": 5
                },
                {
                  "item": "Battery",
                  "quantity": 30
                },
                {
                  "item": "Sensors",
                  "quantity": 20
                },
                {
                  "item": "Exodus Modules",
                  "quantity": 1
                }
              ],
              "crafts": [],
              "label": "Framework (3/6)",
              "progressLabel": "Framework complete",
              "description": "Building walls and roof, installing core systems, and defining the interior layout."
            },
            {
              "level": 4,
              "requirements": [
                {
                  "item": "Humidifier",
                  "quantity": 5
                },
                {
                  "item": "Advanced Electrical Components",
                  "quantity": 5
                },
                {
                  "item": "Magnetic Accelerator",
                  "quantity": 3
                },
                {
                  "item": "Leaper Pulse Unit",
                  "quantity": 3
                }
              ],
              "crafts": [],
              "label": "Outfitting (4/6)",
              "progressLabel": "Outfitting complete",
              "description": "Adding storage, workbenches, utilities, and personal touches."
            }
          ],
          "maxLevel": 4
        },
        {
          "id": "expedition-2",
          "title": "Expedition 2",
          "minLevel": 0,
          "zeroLabel": "Not started",
          "completeLabel": "Outfitting complete",
          "levels": [
            {
              "level": 1,
              "requirements": [
                {
                  "item": "Metal Parts",
                  "quantity": 150
                },
                {
                  "item": "Plastic Parts",
                  "quantity": 200
                },
                {
                  "item": "ARC Alloy",
                  "quantity": 80
                },
                {
                  "item": "Steel Spring",
                  "quantity": 15
                }
              ],
              "crafts": [],
              "label": "Foundation (1/6)",
              "progressLabel": "Foundation complete",
              "description": "Building the base structure and frame of the caravan."
            },
            {
              "level": 2,
              "requirements": [
                {
                  "item": "Durable Cloth",
                  "quantity": 35
                },
                {
                  "item": "Wires",
                  "quantity": 25
                },
                {
                  "item": "Electrical Components",
                  "quantity": 20
                },
                {
                  "item": "Cooling Coil",
                  "quantity": 4
                }
              ],
              "crafts": [],
              "label": "Core Systems (2/6)",
              "progressLabel": "Core Systems complete",
              "description": "Connecting wiring, ventilation, and essential power systems."
            },
            {
              "level": 3,
              "requirements": [
                {
                  "item": "Light Bulb",
                  "quantity": 4
                },
                {
                  "item": "Battery",
                  "quantity": 30
                },
                {
                  "item": "Shredder Gyro",
                  "quantity": 10
                },
                {
                  "item": "Exodus Modules",
                  "quantity": 1
                }
              ],
              "crafts": [],
              "label": "Framework (3/6)",
              "progressLabel": "Framework complete",
              "description": "Building walls and roof, installing core systems, and defining the interior layout."
            },
            {
              "level": 4,
              "requirements": [
                {
                  "item": "Frequency Modulation Box",
                  "quantity": 5
                },
                {
                  "item": "Advanced Electrical Components",
                  "quantity": 5
                },
                {
                  "item": "Ion Sputter",
                  "quantity": 3
                },
                {
                  "item": "Leaper Pulse Unit",
                  "quantity": 3
                }
              ],
              "crafts": [],
              "label": "Outfitting (4/6)",
              "progressLabel": "Outfitting complete",
              "description": "Adding storage, workbenches, utilities, and personal touches."
            }
          ],
          "maxLevel": 4
        },
        {
          "id": "expedition-3",
          "title": "Expedition 3",
          "minLevel": 0,
          "zeroLabel": "Not started",
          "completeLabel": "Outfitting complete",
          "levels": [
            {
              "level": 1,
              "requirements": [
                {
                  "item": "Metal Parts",
                  "quantity": 150
                },
                {
                  "item": "Chemicals",
                  "quantity": 100
                },
                {
                  "item": "ARC Alloy",
                  "quantity": 80
                },
                {
                  "item": "Steel Spring",
                  "quantity": 15
                }
              ],
              "crafts": [],
              "label": "Foundation (1/6)",
              "progressLabel": "Foundation complete",
              "description": "Building the base structure and frame of the caravan."
            },
            {
              "level": 2,
              "requirements": [
                {
                  "item": "Durable Cloth",
                  "quantity": 30
                },
                {
                  "item": "Wires",
                  "quantity": 25
                },
                {
                  "item": "Electrical Components",
                  "quantity": 20
                },
                {
                  "item": "Industrial Charger",
                  "quantity": 3
                }
              ],
              "crafts": [],
              "label": "Core Systems (2/6)",
              "progressLabel": "Core Systems complete",
              "description": "Connecting wiring, ventilation, and essential power systems."
            },
            {
              "level": 3,
              "requirements": [
                {
                  "item": "Coffee Pot",
                  "quantity": 1
                },
                {
                  "item": "Battery",
                  "quantity": 25
                },
                {
                  "item": "Firefly Burner",
                  "quantity": 5
                },
                {
                  "item": "Exodus Modules",
                  "quantity": 1
                }
              ],
              "crafts": [],
              "label": "Framework (3/6)",
              "progressLabel": "Framework complete",
              "description": "Building walls and roof, installing core systems, and defining the interior layout."
            },
            {
              "level": 4,
              "requirements": [
                {
                  "item": "Broken Guidance System",
                  "quantity": 1
                },
                {
                  "item": "Advanced Electrical Components",
                  "quantity": 5
                },
                {
                  "item": "Breathtaking Snow Globe",
                  "quantity": 3
                },
                {
                  "item": "Bombardier Cell",
                  "quantity": 2
                }
              ],
              "crafts": [],
              "label": "Outfitting (4/6)",
              "progressLabel": "Outfitting complete",
              "description": "Adding storage, workbenches, utilities, and personal touches."
            }
          ],
          "maxLevel": 4
        }
      ]
    }
  ]
};
